kind: pipeline
type: docker
name: Compilation of GadgetBridge

workspace:
  path: /drone/src

steps:
- name: generate GadgetBridge
  image: androidsdk/android-29
  pull: if-not-exists
  volumes:
  - name: gradle-cache
    path: /root/.gradle
  commands:
  - GRADLE_OPTS="-XX:MaxPermSize=256m -Dorg.gradle.daemon=false" ./gradlew build connectedCheck --stacktrace
- name: align and signed GadgetBridge
  image: androidsdk/android-29
  pull: if-not-exists
  volumes:
  - name: keystore
    path: /keystore
  commands:
  - cd /drone/src/app/build/outputs/apk/release
  - zipalign -v -p 4 app-release-unsigned.apk app-release-unsigned-aligned.apk
  - apksigner sign --ks /keystore/memiks-release-key.jks --out app-release-signed.apk app-release-unsigned-aligned.apk
  - cd /drone/src/app/build/outputs/apk/debug
  - zipalign -v -p 4 app-debug.apk app-debug-unsigned-aligned.apk
  - apksigner sign --ks /keystore/memiks-release-key.jks --out app-debug-signed.apk app-debug-unsigned-aligned.apk
- name: share artifacts
  image: alpine/git
  volumes:
  - name: data
    path: /data
  pull: if-not-exists
  commands:
  - apk update
  - apk add --no-cache zip alpine-conf
  - setup-timezone -z Asia/Tokyo 
  - export DATE="$(date +%F)"
  - BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
  - echo "$${BRANCH_NAME}/$${DATE}"
  - mkdir -p /data/GadgetBridge/$${BRANCH_NAME}/$${DATE}
  - cd /drone/src/app/build/outputs/apk
  - zip -r -q /data/GadgetBridge/$${BRANCH_NAME}/$${DATE}/debug debug/
  - zip -r -q /data/GadgetBridge/$${BRANCH_NAME}/$${DATE}/release release/
  - cd /drone/src/app/build
  - zip -r -q /data/GadgetBridge/$${BRANCH_NAME}/$${DATE}/reports reports/
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_to
    format: markdown
  when:
    status:
    - failure
    - success

volumes:
  - name: data
    host:
      path: /var/lib/docker/volumes/nginx-web/_data
  - name: gradle-cache
    host:
      path: /opt/dronevolumes/gradle-cache
  - name: keystore
    host:
      path: /opt/dronevolumes/keys