steps:
  tests:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:latest
    commands: |
      pwd
      ./gradlew :app:testBangleDebugUnitTest :app:testMainDebugUnitTest
      if [ $? -ne 0 ]; then
        touch .pipeline_failure
      fi
    failure: ignore

  lint:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:latest
    commands: |
      pwd
      ./gradlew lint

  failure_check:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:latest
    commands: |
      pwd
      if [ -f .pipeline_failure ]; then
        echo "One of the previous steps failed, failing the pipeline"
        exit 1;
      fi

#when:
#repo: Freeyourgadget/Gadgetbridge
#branch: master
#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687

when:
  event:
    exclude: cron
