steps:
  tests:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:latest
    commands:
      - pwd #bump
      - ./gradlew :app:testBangleDebugUnitTest :app:testMainDebugUnitTest
      # mark pipeline as failed if the tests failed, but linter will still run
      - '[ "$CI_STEP_STATUS" == "success" ] || touch .pipeline_failure'
    failure: ignore

  lint:
    image: codeberg.org/freeyourgadget/android-fdroid-tools:latest
    commands:
      - pwd #bump
      - ./gradlew lint
      - if [ -f .pipeline_failure ]; then return 1; fi

#when:
#repo: Freeyourgadget/Gadgetbridge
#branch: master
#this doesn't work yet:
#https://github.com/woodpecker-ci/woodpecker/issues/687

when:
  event:
    exclude: cron
